#!/usr/bin/env ruby
# encoding: utf-8

# Setup a config JSON interactively via a local web page
#
# Usage: run-setup config.json

require "json"
require 'sinatra/base'

if ARGV.length != 1
  STDOUT << "Invalid arguments received, need a config file\n"
  exit 1
end

config_path = File.expand_path(ARGV[0])

class SetupServer < Sinatra::Base
  set :bind, '0.0.0.0'
  set :port, 4568
  set :public_folder, File.expand_path('public', __dir__)
  set :config_path, nil

  get '/' do
    send_file File.join(settings.public_folder, 'setup.html')
  end

  get '/config' do
    content_type :json

    if File.exist?(settings.config_path)
      File.read(settings.config_path)
    else
      {}.to_json
    end
  end

  post '/save' do
    content_type :json

    data = JSON.parse(request.body.read)
    File.write(settings.config_path, JSON.pretty_generate(data))

    { status: 'ok' }.to_json
  end
end

SetupServer.set :config_path, config_path
SetupServer.run!
